options:
  platform:     psx
  basename:     main
  base_path:    ..
  build_path:   build/us
  target_path:  disks/us/SCUS_941.63
  asm_path:     asm/us/main
  asset_path:   assets/us/main
  src_path:     src/main
  ld_script_path: build/us/main.ld
  compiler:     GCC
  symbol_addrs_path:
    - config/symbols.main.us.txt
    - config/sym_extern.us.txt
  create_undefined_funcs_auto: no
  undefined_funcs_auto_path: config/undefined_funcs_auto.us.txt
  create_undefined_syms_auto: yes
  undefined_syms_auto_path:  config/undefined_syms_auto.us.txt
  find_file_boundaries: yes
  use_legacy_include_asm: no
  asm_jtbl_label_macro: jlabel
  disassemble_all: true
  global_vram_start: 0x80010000
  gp_value: 0x80062D44
  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".bss"
  ld_generate_symbol_per_data_segment: true
sha1: a95e8b16b97071203b953bb81a33980509262f30
segments:
  - [0x800, header]
  - name: main
    type: code
    start: 0x00000800
    vram:  0x80010000
    align: 4
    subalign: 4
    subsegments:
      - [0x800, rodata]
      - [0xC38, rodata]
      - [0x18B8, c]
      - [0x19bd0, c, akao]
      - [0x24370, c, psxsdk]
      - [0x394E0, data]
      - [0x5354C, .sdata, 18B8]
      - [0x536C4, bss]
  - [0x61000]
